spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/?user=root
    username: root
    password: slwxyrt12
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.test.bean
